name: Build release zip

on:
  create:
    tags:
      - v*

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build plugin # Remove or modify this step as needed
        run: |
          composer install --no-dev
          npm install
          npm run build

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "cumbersome-canoe.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig"

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "cumbersome-canoe.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
