name: Coding Standards

on: pull_request

jobs:
  phpcs:
    name: WPCS check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: WPCS check
        uses: 10up/wpcs-action@stable
        with:
          standard: "WordPress" # Standard to use. Accepts WordPress|WordPress-Core|WordPress-Docs|WordPress-Extra|WordPress-VIP-Go|WordPressVIPMinimum|10up-Default.
          use_local_config: "true"
